# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rservice.proto\"\x1f\n\x0fStandardRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rStandardReply\x12\x0f\n\x07message\x18\x01 \x01(\t\",\n\rStreamRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"-\n\x0bStreamReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x32\xd3\x03\n\x0bTestService\x12\x32\n\x0cNormalMethod\x12\x10.StandardRequest\x1a\x0e.StandardReply\"\x00\x12\x32\n\x0cStreamMethod\x12\x0e.StreamRequest\x1a\x0e.StandardReply\"\x00\x30\x01\x12\x37\n\x11StreamInputMethod\x12\x10.StandardRequest\x1a\x0c.StreamReply\"\x00(\x01\x12<\n\x12StreamStreamMethod\x12\x10.StandardRequest\x1a\x0e.StandardReply\"\x00(\x01\x30\x01\x12\x44\n\x1aInfiniteStreamStreamMethod\x12\x10.StandardRequest\x1a\x0e.StandardReply\"\x00(\x01\x30\x01\x12\x33\n\rDelayedMethod\x12\x10.StandardRequest\x1a\x0e.StandardReply\"\x00\x12\x35\n\x0f\x45xceptionMethod\x12\x10.StandardRequest\x1a\x0e.StandardReply\"\x00\x12\x33\n\rDelayedStream\x12\x0e.StreamRequest\x1a\x0e.StandardReply\"\x00\x30\x01\x62\x06proto3'
)




_STANDARDREQUEST = _descriptor.Descriptor(
  name='StandardRequest',
  full_name='StandardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='StandardRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=48,
)


_STANDARDREPLY = _descriptor.Descriptor(
  name='StandardReply',
  full_name='StandardReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='StandardReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=82,
)


_STREAMREQUEST = _descriptor.Descriptor(
  name='StreamRequest',
  full_name='StreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='StreamRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='StreamRequest.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=128,
)


_STREAMREPLY = _descriptor.Descriptor(
  name='StreamReply',
  full_name='StreamReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='StreamReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='StreamReply.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['StandardRequest'] = _STANDARDREQUEST
DESCRIPTOR.message_types_by_name['StandardReply'] = _STANDARDREPLY
DESCRIPTOR.message_types_by_name['StreamRequest'] = _STREAMREQUEST
DESCRIPTOR.message_types_by_name['StreamReply'] = _STREAMREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StandardRequest = _reflection.GeneratedProtocolMessageType('StandardRequest', (_message.Message,), {
  'DESCRIPTOR' : _STANDARDREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:StandardRequest)
  })
_sym_db.RegisterMessage(StandardRequest)

StandardReply = _reflection.GeneratedProtocolMessageType('StandardReply', (_message.Message,), {
  'DESCRIPTOR' : _STANDARDREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:StandardReply)
  })
_sym_db.RegisterMessage(StandardReply)

StreamRequest = _reflection.GeneratedProtocolMessageType('StreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:StreamRequest)
  })
_sym_db.RegisterMessage(StreamRequest)

StreamReply = _reflection.GeneratedProtocolMessageType('StreamReply', (_message.Message,), {
  'DESCRIPTOR' : _STREAMREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:StreamReply)
  })
_sym_db.RegisterMessage(StreamReply)



_TESTSERVICE = _descriptor.ServiceDescriptor(
  name='TestService',
  full_name='TestService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=178,
  serialized_end=645,
  methods=[
  _descriptor.MethodDescriptor(
    name='NormalMethod',
    full_name='TestService.NormalMethod',
    index=0,
    containing_service=None,
    input_type=_STANDARDREQUEST,
    output_type=_STANDARDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamMethod',
    full_name='TestService.StreamMethod',
    index=1,
    containing_service=None,
    input_type=_STREAMREQUEST,
    output_type=_STANDARDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamInputMethod',
    full_name='TestService.StreamInputMethod',
    index=2,
    containing_service=None,
    input_type=_STANDARDREQUEST,
    output_type=_STREAMREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamStreamMethod',
    full_name='TestService.StreamStreamMethod',
    index=3,
    containing_service=None,
    input_type=_STANDARDREQUEST,
    output_type=_STANDARDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='InfiniteStreamStreamMethod',
    full_name='TestService.InfiniteStreamStreamMethod',
    index=4,
    containing_service=None,
    input_type=_STANDARDREQUEST,
    output_type=_STANDARDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DelayedMethod',
    full_name='TestService.DelayedMethod',
    index=5,
    containing_service=None,
    input_type=_STANDARDREQUEST,
    output_type=_STANDARDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ExceptionMethod',
    full_name='TestService.ExceptionMethod',
    index=6,
    containing_service=None,
    input_type=_STANDARDREQUEST,
    output_type=_STANDARDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DelayedStream',
    full_name='TestService.DelayedStream',
    index=7,
    containing_service=None,
    input_type=_STREAMREQUEST,
    output_type=_STANDARDREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTSERVICE)

DESCRIPTOR.services_by_name['TestService'] = _TESTSERVICE

# @@protoc_insertion_point(module_scope)
